name: C/C++ CI

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: write file
      run: echo -e "#include <iostream>\n#include \"FFTReal.h\"\n\nint main (int argc, char *argv[])\n{\n    fftpp::FFTReal<float_t> fftF (512);\n    fftpp::FFTReal<int32_t> fftI (512);\n}" > main.cpp
    - name: compile and run
      run: g++ -std=c++17 main.cpp -o a.out && ./a.out
      
